cmake: correct flags for crc32_acle.c in aarch64 case?
Without this, build fails with
arm_acle.h:71:1: error: inlining failed in call to always_inline ‘__crc32h’: target specific option mismatch
because crc32_acle.c was being built without -march flags on aarch64.